server:
  port: 8080

spring:
  application:
    name: EVENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/eventaggrigator
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: eventaggrigator
    username: root
    password: Vishal@4545

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      file-size-threshold: 1KB
      max-file-size: 50MB
      max-request-size: 50MB
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
      
