server:
  port: 9191
spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: event-module
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-79462779.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true