server:
  port: 9191

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: pgateway-module
          uri: lb://EVENT-PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**

        - id: event-module
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
