spring:
  application:
    name: EVENT-PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/eventaggrigator
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: eventaggrigator
    username: root
    password: Vishal@4545
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8585

razorpay:
  key_id: rzp_test_U6LXs2MWCEfepJ
  key_secret: QTFDzsD2iyGLXMWDe50sf8kY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: true
      